CREATE TABLE [dbo].[UserData]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Email] NVARCHAR(MAX) NOT NULL, 
    [PasswordHash] NVARCHAR(MAX) NOT NULL, 
    [PasswordSalt] NVARCHAR(MAX) NOT NULL, 
    [Role] NVARCHAR(MAX) NOT NULL
)
